### ISSUE TITLE
Vertaisarviointi, viikko 5

### ISSUE THREAD

**Issue by rheikkinen** [TopiasHarjunpaa/C4AI#1]
Projekti kloonattu 17.8. klo 13.10

### Ohjelman toiminta 
Ohjelman toiminnassa ei noussut esiin oikeastaan mitään ongelmia. Peli toimii odotetusti, eli sitä voi pelata tietokonetta vastaan, ja tekoälylle on toteutettu jopa useampi vaikeustaso. Tekoäly, erityisesti siis syvyyden 7 minimaxilla ja optimoidulla minimaxilla, osaa valita siirtonsa oikein järkevästi ja nopeasti, ja se ei todella ollut helppo vastus. Komentorivin tulostukset olivat myös kuvaavia ja helpottivat kokeilua ja algoritmien vertailua.

Pelin käyttöliittymäkin toimii sujuvasti, kaikki toiminnot on helposti ymmärrettävissä, ja navigointi valikoissa on helppoa.

### Ohjelman koodi ja rakenne 
Ohjelma on melko laaja, mutta se on pilkottu järkeviin hakemistoihin ja selkeästi nimettyihin moduuleihin. Koska dokumentointikin on kattavasti kirjoitettu, kaikista ohjelman osista sai melko pienellä vaivalla käsityksen, mikä minkäkin vastuualueena on. Ohjelman laajuus huomioiden, täytyy sanoa, että koodi oli varsin sujuvasti luettavaa. Toki osansa auttoi varmaan sekin, että oman projektin aihe on samanlainen, niin toteutukset olivat senkin vuoksi helpommin ymmärrettävissä.

Koodin toteutuksissa ei sen kummemmin herännyt moitittavaa. Mahtavaa, että projektiin on löydetty ja siinä on hyödynnetty monipuolisesti mielenkiintoisia toteutustapoja, mm. bitboard ja transposition table, joilla laskentanopeus ja -syyvydet on saatu hyvälle tasolle.

Pienenä huomioida tuli mieleen, onko metodien ja muuttujien nimiä välillä liikaakin lyhennetty luettavuuden kustannuksella. Muutamana poimintana esim: 
#### ai_service.py
- metodi `_minimax_with_id_and_bb`
    - Tämä nousi esimerkiksi, koska en tosiaan heti osannut yhdistää, että id --> iterative deepening, muuten toki ymmärrettävän haastavaa keksiä kuvaavaa nimeä.
#### heuristic_service.py
- metodi `calculate_heuristic_value_w_bbs` 
    - voisiko metodin nimeksi riittää esim. `calculate_value_with_bitboards` 
#### situation_service.py: 
- muuttuja `loc` metodissa `check_win`

Eivät nämä suuresti ongelmia aiheuttanut, mutta yleisesti hyvä muistaa, että lyhenteet heikentävät lähes aina koodin luettavuutta erityisesti ulkopuolisen tarkastelijan näkökulmasta, jolle merkitykset eivät välttämättä ole itsestään selviä. Jos mahdollista, monesti on parempi käyttää pidempää ja kuvaavampaa nimeä.

Lisäksi huomio **situation_service.py**:n metodista `check_column_available`:

Metodi palauttaa rivi-indeksin, jos sarake on vapaa, tai -1, jos sarake on täynnä. Koska sitä käytetäänkin nyt erityisesti myös rivin hakemiseen (`row = situation.check_column_available(grid, col)`), metodin nimi ei ehkä kuvaa sen toimintaa aivan selvästi. Nimeä voisi muuttaa kuvaavammaksi, tai mahdollisesti voisi erotella sarakkeen vapauden tarkistuksen ja vapaan rivin hakemisen eri metodeihin.

### Testaus 
Yksikkötestien ajaminen onnistui, ja kaikki testit menivät läpi, hyvä! Ohjelman eri osia on myös testattu monipuolisesti, ja testit vaikuttavat testaavan järkeviä asioita.  Itse testitapauksetkin on nimetty kuvaavasti. 

Peliruudukon eri tilanteiden hakeminen `test_grids.py`-tiedostosta on hyvä idea. Tässäkin huomio kiinnittyi nimeämisiin, testiruudukoiden nimet voisivat olla hieman kuvaavampia. Verraten kun nyt kirjain-numeroyhdistelmistä oli vaikea tehdä suoraan juuri mitään tulkintoja, ja joutui hieman seilaamaan tiedostojen välillä, jotta ymmärsi millaista tilannetta missäkin assert-tarkistuksessa testataan.

Ymmärrettävästi pelitilanteita ei voi kaikenkattavasti kuvata kovin lyhyesti, eikä tämä(kään) ole suuri ongelma. Tässä kuitenkin yksi vaihtoehtoinen toteutus, joka itselle tuli mieleen.

**Muutetaan ruudukoiden nimiä, esim:**
- `G_DD1` --> `P1_DOWN_DIAGONAL_WIN`
- `G_WO1` --> `FULL_NO_WINNER` 

**Esimerkki `situation_service_test.py`:stä**
``` 
import tests.test_grids as GRID 
    # ...    
    def test_check_win_finds_down_diagonal_win(self):
        # ...
        self.assertTrue(self.situation.check_win(GRID.P1_DOWN_DIAGONAL_WIN, 1)) 
        self.assertFalse(self.situation.check_win(GRID.FULL_NO_WINNER, 1)) 
```
### Yhteenveto
Projektiin on selvästi hyvin panostettu ja se on määrittelydokumenttiin katsoen erinomaisessa vaiheessa. Vaikea tuosta oli parannettavaakaan löytää, joten huomio kiinnittyi pitkälti toiminnan kannalta vähemmän merkityksellisiin asioihin. Hyvin toteutettu projekti, jota oli mukava arvioida. Jatka samaan malliin!

**Comment by TopiasHarjunpaa** [comment]
Kiitos mainioista kommenteista ja erittäin perustelluista huomioista! Jälkikäteen tarkasteltuna on hauska huomata, kuinka helppoa on sokeutua omalle toteutuksella. Itse tuskin näihin olisin enää kiinnittänyt huomiota, vaikka nyt mainitsemisesi jälkeen vaikuttavatkin ilmiselviltä  :) Toki myönnettäköön, että houkutus lyhenteille kasvaa varsinkin, jos pylint antaa herjaa liian pitkistä riveistä...

Päädyin tekemään korjaukset metodi ja muuttujanimille kaikissa ehdottamissasi kohdissa pois lukien `test_grids.py` peliruudukoiden nimet (lähinnä omasta laiskuudestani johtuen). Ehkä mahdollisesti korjaan nuokin ennen loppupalautusta, mikäli intoa riittää loppuun asti.
