### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by ethanrailo** [TopiasHarjunpaa/C4AI#2]
Projekti kloonattu 25.8 klo 6.

Sovellus toimi oletetusti kloonaamisen jälkeen ja näytti myös siltä, että siihen on käytetty aikaa ja vaivaa :-) Eli hieno ja laaja toteutus, näyttäisi täyttävän ja ylittävänkin reippaasti alkuperäisen määrittelydokumentin. Tekoäly oli myös vaikeimmilla tasoilla selkeästi tehtävänsä tasolla ja voitti pelejä ainakin allekirjoittanutta vastaan.

Koodin puolelta ensimmäinen havainto on se, että sitä on varsin paljon laajuudesta johtuen, mutta se on hyvin jaoteltu. Jaottelu tekee lukemisen helpoksi ja ilman aiempaa tuntemusta implementoimistasi algoritmeista on silti mahdollista pysyä kohtuullisesti kärryllä, koska myös docstringit ovat oikein kattavasti ja selkeästi kirjoitettu. Koodi oli selkeää, ytimekästä ja muuttujat/metodit olivat asiallisesti nimettyjä. Koodin puolelta ei minulla ole tarjota edes puolivillaisia parannusehdotuksia.

Testit vaikuttivat myös järkeviltä, eikä minulla ole niihin lisäyksiä ehdottaa. Sellainen pieni henkilökohtainen preferenssi kyllä, että testidokumentin perusteella esim. game_servicen osalta ei ole tarkoituskaan testata tiettyjä juttuja, niin voisiko ne excludaa testikattavuudesta soveltuvalla kommentilla myös koodissa? Tämä tietenkin on luokkaa "turhaa nipotusta", mutta työstäsi on vaikeaa keksiä sitä kuuluisaa oikeaa korjattavaa.

Yhteenvetona voisi siis todeta, että hyvää työtä ja panostaminen näkyy läpi projektin aina repositoriosta valmiiseen tuotokseen ja samaan aikaan tekninen perusta on hyvin rakenettu!

**Comment by TopiasHarjunpaa** [comment]
Kiitos kommenteista ja pahoittelut myöhäisestä vastauksesta! Tuo ehdoittamasi testien kommentointi onkin varmasti järkevä käytäntö. Pysyisi itsekin paremmin kärryllä siitä, mistä vielä tarpeelliset testit puuttuvat. Tsemppiä loppuprojektiin ja hyvät kesän loput!
